Vagrant::Config.run do |config|
  require "./.config/config"

  Vm.descendants.each_with_index do |vm,count_vms|
    (1..vm::Count).each do |index|
      # Initialize & set counters
      count = ""
      formatted_count = ""
      if vm::Count > 1
        count = "#{index}"
        formatted_count = "(#{index}of#{vm::Count})"
      end

      config.vm.define "#{vm::Shortname}#{index}" do |vm_config|

        vm_config.vm.box = vm::Basebox
        vm_config.vm.box_url = vm::Box_url
        vm_config.vm.auto_port_range = Conf::SSH_range
        vm_config.vm.network :hostonly, "#{Conf::Network}.#{Conf::Subnet}.#{Conf::Host_IP + ((count_vms) * 10) + index - 1}"
        hostname = "#{vm::Shortname}#{count}.#{Conf::Project}.#{vm::Domain}"
        vm_config.vm.host_name = hostname
        vm_config.vm.customize ["modifyvm", :id, "--name", "#{vm::Longname}#{formatted_count}(#{hostname})"]
        vm_config.vm.customize ["modifyvm", :id, "--memory", "#{vm::Memory}"]
        if defined?(vm::NFS_shares)
          vm::NFS_shares.each do |name, path|
            vm_config.vm.share_folder(name, path, "./#{name}", { :nfs => true, :create => true, :remount => true })
          end
        end
        if vm::Gui == true
          vm_config.vm.boot_mode = :gui
        end

        if File::exists?("#{vm::Manifests}/#{vm::Site}.pp")
          vm_config.vm.provision :puppet do |puppet|
            puppet.manifest_file = "#{vm::Site}.pp"
            # Initialize an empty array so we can push onto it
            puppet.module_path = []
            # Merge in project-specific Puppet modules
            vm::Modules.update(Conf::Modules)
            vm::Modules.each do |name,path|
              # Expand relative paths (such as '~')
              full_path = File.expand_path("#{path}")
              # Cull directories that don't exist
              # TODO: Figure out what we're doing here, and why
              if File::directory?("#{full_path}")
                puppet.module_path.push("#{full_path}")
              end
            end
            puppet.facter = Conf::Facts.update(vm::Facts)
            puppet.options = vm::Options
            if vm::Debug == true
              puppet.options = puppet.options + " --debug"
            end
            if vm::Verbose == true
              puppet.options = puppet.options + " --verbose"
            end
          end
        end

      end

    end
  end

end
